LB-708: Merge the __init__.py and utils.py in stats directory.
metabrainz/listenbrainz-server pull request #1051
Opened 2020-08-24 14:36 UTC by AbhinavOhri

# Problem

LB-708

# Solution
Merged utils.py and init.py in stats directory

2020-08-24 14:36 UTC, pep8speaks commented
Hello @AbhinavOhri! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`listenbrainz_spark/stats/__init__.py`](https://github.com/metabrainz/listenbrainz-server/blob/bc33088e66754fc74ea7195e351429e32f620e4a/listenbrainz_spark/stats/__init__.py):

> [Line 9:43](https://github.com/metabrainz/listenbrainz-server/blob/bc33088e66754fc74ea7195e351429e32f620e4a/listenbrainz_spark/stats/__init__.py#L9): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-08-26 16:21 UTC, paramsingh requested changes

2020-08-26 16:21 UTC, paramsingh commented on listenbrainz_spark/stats/__init__.py
> +from listenbrainz_spark.stats import utils
This isn't ideal, I'd prefer to move these functions to utils and then change the places where they're imported to utils as well. Right now, if i want to get to the definition of a function, I'd have to go here, figure out that this file imports utils and then go to utils. if we fix the imports, the reader can directly reach utils.

2020-09-04 08:10 UTC, paramsingh approved these changes

2020-09-04 08:10 UTC, merged

2020-09-04 08:54 UTC, paramsingh commented
FYI: I had to revert this in https://github.com/metabrainz/listenbrainz-server/commit/a12670663b5ed655b3e7299906d6ef7f1cea4e17, looks like the master build failed because of some imports

2020-09-17 18:56 UTC, AbhinavOhri commented
@paramsingh  Should I try to fix this and open another PR?