Update spark config values to try and avoid RPC client error
metabrainz/listenbrainz-server pull request #1088
Opened 2020-09-13 05:32 UTC by vansika

`ERROR TaskSchedulerImpl: Lost executor 2 on 10.0.1.24: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.`

I am still not sure what causes the above error in `train_models.py`.  I have tweaked the spark configs.

I also have added a few log messages to understand which process is exactly causing the error.

2020-09-13 09:05 UTC, paramsingh requested changes

2020-09-13 09:05 UTC, paramsingh commented on listenbrainz_spark/recommendations/train_models.py
> +    # commenting out till we are sure that the cached data isn't causing RPC errors.
let's remove the lines, it's easy to get them back from git, and it's generally very easy to forget about things like this.

2020-09-14 16:15 UTC, paramsingh approved these changes

2020-09-14 16:15 UTC, paramsingh commented on listenbrainz/webserver/templates/emails/cf_recording_model_upload_notification.txt
> +time taken to create model = {{ total_time }}s
unrelated change?

2020-09-14 16:15 UTC, merged

2020-09-14 16:16 UTC, vansika commented on listenbrainz/webserver/templates/emails/cf_recording_model_upload_notification.txt
> +time taken to create model = {{ total_time }}s
No.