LB-579: Improve pagination buttons on "Recent Listens" and "User Artists" page
metabrainz/listenbrainz-server pull request #1211
Opened 2020-12-27 11:57 UTC by kshitijk83

# Problem

    The pagination buttons in "Recent LIstens" and User Entity Chart"should use "disabled" style instead of "hidden".
    https://tickets.metabrainz.org/browse/LB-579

# Solution

Changed classname from  "hidden" to "disabled"

2020-12-27 11:59 UTC, shivam-kapila requested changes
Looks good. Can you please update the test snapshots by running `./test.sh fe -u`. Otherwise it will break the tests once the admins verify the patch.

2020-12-29 11:52 UTC, shivam-kapila reviewed
Thanks for updating the snapshots. This looks okay now but I'd wait for the test results. @alastair can you please whitelist them.

2021-01-04 09:25 UTC, alastair commented
@brainzbot add to whitelist

2021-01-04 15:54 UTC, kshitijk83 commented
Are these failed tests relevant here ? Do i need to make some changes?

2021-01-11 17:52 UTC, MonkeyDo approved these changes
Thanks for the PR @kshitijk83 ! 
This is a good improvement, it's been bothering me for a while :)

The failing tests are unrelated to the changes in the PR, so I'll go ahead and merge it.

2021-01-11 17:53 UTC, merged