LB-802: Last.fm importer user friendliness improvements
metabrainz/listenbrainz-server pull request #1251
Opened 2021-01-22 01:24 UTC by jdaok

# Problem
[LB-802](https://tickets.metabrainz.org/browse/LB-802)

1. https://community.metabrainz.org/t/request-clarify-importer-restart-text/506204
The last.fm importer restart text is vague and should be clarified

2. https://community.metabrainz.org/t/problem-with-import-from-last-fm/454546
When the user's last.fm is private, the error message is unrelated and unhelpful ("The number submitted listens is different from the that Last.fm reports due to an inconsistency in their API, sorry!")

3. https://tickets.metabrainz.org/browse/LB-258
The last.fm username input should remember the username so it doesn't have to be typed repeatedly.

# Solution

1. Updated general restart text
![image](https://user-images.githubusercontent.com/57575778/105432108-d271c880-5c0b-11eb-87de-2db21638d85e.png)

2. Added catching for last.fm privacy error and changed error message
![image](https://user-images.githubusercontent.com/57575778/105432157-ef0e0080-5c0b-11eb-88fe-80cca0f4637b.png)

3. HTML input box should now suggest previous inputted usernames on most browsers
![image](https://user-images.githubusercontent.com/57575778/105432267-2e3c5180-5c0c-11eb-92f6-1d02ec7705c5.png)

- fixed eslint error from my previous commit  (Expected 'this' to be used by class method)

2021-02-05 12:45 UTC, MonkeyDo requested changes
Looks good so far, thanks for opening this PR and continuing to improve the importer :)

2021-02-05 12:45 UTC, MonkeyDo commented on listenbrainz/webserver/static/js/src/LastFMImporter.tsx
> +    const response = await fetch(encodeURI(url));
Let's add a try-catch block around this await to catch any errors with that fetch call.

What should happen if the fetch fails ? (for example a temporary network issue)
Once that is decided, you can add a test with a simulated failure of the fetch with something like `window.fetch.mockImplementationOnce(() => Promise.reject("Some error"));`

2021-04-21 16:22 UTC, MonkeyDo commented
Hi @jdaok !
Can I help you with anything on this PR? I'd love to see those improvements merged :)
Let me know if you have any question !

2021-04-27 22:26 UTC, pep8speaks commented
Hello @jdaok! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`listenbrainz/db/follow_list.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/db/follow_list.py):

> [Line 8:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/db/follow_list.py#L8): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1





* In the file [`listenbrainz/db/tests/test_follow_list.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/db/tests/test_follow_list.py):

> [Line 21:5](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/db/tests/test_follow_list.py#L21): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 38:5](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/db/tests/test_follow_list.py#L38): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 77:5](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/db/tests/test_follow_list.py#L77): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)













* In the file [`listenbrainz/follow_server/dispatcher.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/dispatcher.py):

> [Line 10:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/dispatcher.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 42:131](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/dispatcher.py#L42): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 130 characters)

* In the file [`listenbrainz/follow_server/follow_server.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py):

> [Line 4:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L4): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 5:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L5): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 6:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L6): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 7:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L7): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 8:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L8): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 10:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 12:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 21:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L21): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 51:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/follow_server/follow_server.py#L51): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

































* In the file [`listenbrainz/webserver/views/follow.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/follow.py):

> [Line 11:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/follow.py#L11): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`listenbrainz/webserver/views/follow_api.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/follow_api.py):

> [Line 14:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/follow_api.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1











* In the file [`listenbrainz/webserver/views/test/test_follow.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/test/test_follow.py):

> [Line 60:34](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/test/test_follow.py#L60): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment







* In the file [`listenbrainz/webserver/views/user.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/user.py):

> [Line 224:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/user.py#L224): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 287:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/user.py#L287): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 345:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/listenbrainz/webserver/views/user.py#L345): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`manage.py`](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/manage.py):

> [Line 38:1](https://github.com/metabrainz/listenbrainz-server/blob/607490c82603018887ae0cf333c12fa680ac4c85/manage.py#L38): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-04-29 02:12 UTC, jdaok commented
Moved to https://github.com/metabrainz/listenbrainz-server/pull/1417

2021-04-29 02:12 UTC, closed without merging