Add API endpoint to create user track recommendations
metabrainz/listenbrainz-server pull request #1311
Opened 2021-03-02 18:03 UTC by paramsingh

# Problem

We want users to be able to recommend tracks from their listens to their followers.

# Solution

This PR does the following:
* Adds an API endpoint to create track recommendation events.
* Adds a barebones JS client method to use on the frontend side.

# Action

2021-03-02 18:03 UTC, pep8speaks commented
Hello @paramsingh! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`data/model/user_timeline_event.py`](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/data/model/user_timeline_event.py):

> [Line 25:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/data/model/user_timeline_event.py#L25): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 28:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/data/model/user_timeline_event.py#L28): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 37:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/data/model/user_timeline_event.py#L37): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 39:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/data/model/user_timeline_event.py#L39): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`listenbrainz/db/tests/test_user_timeline_event.py`](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/db/tests/test_user_timeline_event.py):

> [Line 30:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/db/tests/test_user_timeline_event.py#L30): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`listenbrainz/db/user_timeline_event.py`](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/db/user_timeline_event.py):

> [Line 23:131](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/db/user_timeline_event.py#L23): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 130 characters)
> [Line 37:17](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/db/user_timeline_event.py#L37): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 61:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/db/user_timeline_event.py#L61): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`listenbrainz/tests/integration/test_user_timeline_event_api.py`](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/tests/integration/test_user_timeline_event_api.py):

> [Line 29:1](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/tests/integration/test_user_timeline_event_api.py#L29): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 64:5](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/tests/integration/test_user_timeline_event_api.py#L64): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 95:5](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/tests/integration/test_user_timeline_event_api.py#L95): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 107:5](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/tests/integration/test_user_timeline_event_api.py#L107): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)



* In the file [`listenbrainz/webserver/views/user_timeline_event_api.py`](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/webserver/views/user_timeline_event_api.py):

> [Line 45:5](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/webserver/views/user_timeline_event_api.py#L45): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 59:5](https://github.com/metabrainz/listenbrainz-server/blob/14144c2e27e093abaa1f4bdca071d74e9545ac5c/listenbrainz/webserver/views/user_timeline_event_api.py#L59): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2021-03-02 18:04 UTC, paramsingh commented on admin/sql/updates/2021-03-02-add-user-recommendation-event-table.sql
> +CREATE TYPE user_timeline_event_type_enum AS ENUM('recording_recommendation');
This was a change that should have been in #1309 but I missed it.

2021-03-02 18:04 UTC, paramsingh commented on manage.py
> +from time import sleep
Noticed some missing imports in manage.py so thought I'd add them

2021-03-02 18:07 UTC, paramsingh commented
I'll fix the pep8 things after code review tomorrow,

2021-03-03 12:11 UTC, mayhem requested changes
See comments -- also docstrings are missing and I would like to see them at the very least for the API endpoints.

2021-03-03 12:11 UTC, mayhem commented on listenbrainz/webserver/views/user_timeline_event_api.py
> +def create_user_recommendation_event():
The function name should also be changed to reflect the updated URL, I think. create_timeline_event_recroding ?

2021-03-03 12:11 UTC, mayhem commented on listenbrainz/webserver/views/user_timeline_event_api.py
> +    except pydantic.ValidationError:
Can we pass a more useful message to the user?

2021-03-03 12:11 UTC, mayhem commented on listenbrainz/webserver/views/user_timeline_event_api.py
> +    except pydantic.ValidationError:
In the block above as well.

2021-03-03 12:11 UTC, mayhem commented on listenbrainz/tests/integration/test_user_timeline_event_api.py
> +            '/1/user-timeline-event/create-user-recommendation/recording',
Use url_for here?

2021-03-03 13:25 UTC, paramsingh commented on data/model/user_timeline_event.py
> +    spotify_id: Optional[str]
Removed the spotify ID here, I was keeping it as it'd be helpful for brainzplayer, but I think we rely on search anyways, so should be ok.

2021-03-03 13:25 UTC, paramsingh commented on listenbrainz/db/user_timeline_event.py
> +def get_user_timeline_events(user_id: int, event_type: UserTimelineEventType, count: int = 50) -> List[UserTimelineEvent]:
These functions were only really for tests, I'm gonna add more pagination support in future PRs focussed on retrieving these events. This PR is only about creation of the events.

2021-03-03 13:26 UTC, mayhem commented on data/model/user_timeline_event.py
> +    spotify_id: Optional[str]
👍

2021-03-03 13:26 UTC, paramsingh commented
please take a look, @mayhem

2021-03-03 13:44 UTC, mayhem approved these changes
Thanks for making those changes! LGTM pending passing tests.

2021-03-03 13:47 UTC, merged