LB-773: Remove pytz dependency
metabrainz/listenbrainz-server pull request #1337
Opened 2021-03-12 13:46 UTC by dpmittal

# Problem
ListenBrainz uses pytz for pytz.UTC function whereas in new python datetime has timezone.utc which should be used instead.

# Solution
Removed pytz dependency from the project and used timezone.UTC wherever needed.

# Action

2021-03-12 15:17 UTC, shivam-kapila requested changes
Hi. Thanks for the PR :). Looks good overall, just some unnecessary imports

2021-03-12 15:17 UTC, shivam-kapila commented on listenbrainz/tests/utils.py
> +from datetime import datetime, timezone
same here

2021-03-12 15:19 UTC, dpmittal commented on listenbrainz/tests/utils.py
> +from datetime import datetime, timezone
Sure understood I'll remove that

2021-03-12 15:25 UTC, shivam-kapila approved these changes

2021-03-12 15:25 UTC, shivam-kapila commented on listenbrainz/db/spotify.py
> +from datetime import datetime, timezone
oh I deleted this comment by mistake. Please remove this too. Sorry

2021-03-12 15:31 UTC, dpmittal commented
@shivam-kapila I have made the changes now. Can you please check?

2021-03-12 17:24 UTC, shivam-kapila commented
LGTM. Lets wait for the admins to whitelist this

2021-03-12 17:29 UTC, shivam-kapila approved these changes
LGTM. Lets wait for the admins to whitelist this

2021-03-17 18:48 UTC, alastair commented
@brainzbot ok to test

2021-03-17 18:49 UTC, alastair approved these changes
Looks good, thanks!

and thanks @shivam-kapila for the pre-review too!

2021-03-18 11:20 UTC, alastair commented
@brainzbot test this please

2021-03-18 12:09 UTC, merged

2021-03-18 13:30 UTC, dpmittal commented
Thanks @shivam-kapila  and @alastair once again for reviewing and merging the changes :D