LB-774: Fix Sphinx Documentation Warnings
metabrainz/listenbrainz-server pull request #1340
Opened 2021-03-13 10:51 UTC by dpmittal

# Problem

Many Sphinx warnings were coming up while building the documentation locally which needed to be fixed as shown in https://tickets.metabrainz.org/browse/LB-774

# Solution

The warnings were coming up due to improper indentation in JSON code-block examples and some other bugs in documentation.

# Action

1. In this file `docs/dev/spark-devel-env.rst`:- The `info` wasn't a proper directive so change it to `seealso` as per my comprehension but yes directives like `note` can be used.
2.  In the toctree in file `docs/index.rst`:- I have just added the left out rst files at the end but might have to change the ordering of the index.

2021-03-13 10:51 UTC, pep8speaks commented
Hello @dpmittal! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`listenbrainz/webserver/views/api.py`](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/api.py):

> [Line 438:1](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/api.py#L438): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`listenbrainz/webserver/views/playlist_api.py`](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/playlist_api.py):

> [Line 539:23](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/playlist_api.py#L539): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 540:16](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/playlist_api.py#L540): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 541:14](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/playlist_api.py#L541): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 590:17](https://github.com/metabrainz/listenbrainz-server/blob/148ba62555ff6df9e52140af14972c8ee459139c/listenbrainz/webserver/views/playlist_api.py#L590): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2021-03-13 19:06 UTC, shivam-kapila requested changes

2021-03-13 19:06 UTC, shivam-kapila commented on listenbrainz/webserver/views/api.py
> +        }
```suggestion
        {
            "user_name": "hwnrwx",
            "similarity": 0.1938480256
        }
```
Please update the indentation for all other jsos too.

2021-03-17 18:42 UTC, alastair commented
@brainzbot ok to test

2021-03-17 18:44 UTC, alastair commented
thanks for the changes @dpmittal, it's great to see no warnings!

I think that we should use `..note` in spark-devel-env instead of seealso.

Is it possible to make develop-sh.rst appear as a sub-section of `devel-env.rst` or would that involve moving the contents from one file to the other? At the very least we should group them together so that "Using develop.sh" comes after "Set up ListenBrainz Server development environment"

2021-03-18 12:34 UTC, merged

2021-03-18 12:35 UTC, alastair commented
I made the changes that I suggested. I was able to move develop-sh into the page for setting up the development environment. thanks again

2021-03-18 13:29 UTC, dpmittal commented
Thanks a lot, @alastair for reviewing and merging the changes :D Apologies, actually I just saw your suggestions but till then you had committed them