Change IRC references to Libera.Chat
metabrainz/listenbrainz-server pull request #1491
Opened 2021-05-29 13:48 UTC by amCap1712

2021-05-30 14:19 UTC, shivam-kapila requested changes

2021-05-30 14:19 UTC, shivam-kapila commented on README.md
> +or come visit us in the #metabrainz IRC channel on irc.libera.net.
```suggestion
or come visit us in the #metabrainz IRC channel on irc.libera.chat.
```

2021-05-30 14:19 UTC, shivam-kapila commented on listenbrainz/webserver/templates/index/contribute.html
> +     project to get started. You may also consider heading to our IRC channel #metabrainz on irc.libera.net and
```suggestion
     project to get started. You may also consider heading to our IRC channel #metabrainz on irc.libera.chat and
```

2021-05-30 14:38 UTC, amCap1712 commented
@shivam-kapila Thanks!

2021-05-31 11:32 UTC, alastair approved these changes
Looks good. Do we also have a template repository that contains this information?

2021-05-31 11:36 UTC, amCap1712 commented
@alastair Yes, it has already been updated. https://github.com/metabrainz/.github/pull/2

2021-05-31 11:36 UTC, merged