Implement pinned track table
metabrainz/listenbrainz-server pull request #1492
Opened 2021-06-01 05:10 UTC by jdaok

This PR aims to adds the pinned track table to the database and contains the corresponding SQL update script.

After the script is run the table looks like this:
![image](https://user-images.githubusercontent.com/57575778/120269041-dec1fe00-c25b-11eb-9343-f3e7ecad8410.png)

2021-06-01 12:52 UTC, mayhem commented
We had a quick chat about this feature and sorted out the smaller details of how we want this to function. See our logs here: https://chatlogs.metabrainz.org/libera/metabrainz/2021-06-01/?msg=4814022&page=2

In summary, we'd like:

- Pinned tracks to stay pinned for a week, then "unpin" themselves.
- We'd like the user to be able to unpin a track, if they wish.
- We'd like the user to be able to delete pinned tracks.
- We'd like to avoid adding a periodic job to unpin tracks.

To accomplish all of the above, one change will be necessary to the schema. I'll leave a detailed comment in the file in question.

2021-06-01 12:59 UTC, mayhem requested changes
This looks quite good, contrary to what you might think, regardless of the numerous comments on this PR. :) Some minor changes and this should be good to go.

2021-06-01 12:59 UTC, mayhem commented on admin/sql/create_tables.sql
> +    currently_pinned        BOOLEAN NOT NULL DEFAULT TRUE,
Let's replace this with "pinned_until TIMESTAMP WITH TIME ZONE NOT NULL". This way when a track is pinned, we set this value to now() + 1 week. Then in the view that displays the user's pinned tracks we can look if the pin has expired and adjust the text accordingly. (e.g. This user has this pinned track X OR This user's last pinned track was X)

2021-06-01 12:59 UTC, mayhem commented on admin/sql/updates/2021-05-30-add-pinned-track-table.sql
> +    currently_pinned        BOOLEAN NOT NULL DEFAULT TRUE,
Fix this too, obvs. :)

2021-06-01 12:59 UTC, mayhem commented on admin/sql/create_indexes.sql
> +CREATE UNIQUE INDEX user_id_rec_mbid_ndx_pinned_track ON pinned_track (user_id, recording_mbid);
We're unlikely to want to fetch data from this table using both user_id and recording_mbid. The normal pattern I expect is to ask "what recordings does this user have pinned"? So, this index should be on user_id only.

2021-06-01 12:59 UTC, mayhem commented on admin/sql/create_tables.sql
> +    blurb_content           VARCHAR,
In other places we would normally use TEXT here.

2021-06-01 12:59 UTC, mayhem commented on admin/sql/create_tables.sql
> +CREATE TABLE pinned_track (
Let's call this pinned_recording, since we're pinning recordings and not tracks (the MB db actually has tracks, which are distinct from recordings).

2021-06-01 13:27 UTC, mayhem commented on admin/sql/create_indexes.sql
> +CREATE UNIQUE INDEX user_id_rec_mbid_ndx_pinned_track ON pinned_track (user_id, recording_mbid);
Also, this should not be a UNIQUE index, otherwise a user can never pin the same track twice.

2021-06-02 05:33 UTC, jdaok commented
Thank you @mayhem, I've made the necessary changes. 
I read the discussion on IRC and my understanding for how the table will function is this (please correct me if I'm wrong)
- Instead of using the currently_pinned column, we will determine the active pin by comparing the current time (now()) to pinned_until.
- When unpinning a recording, we will update the pinned_until to the current time and it won't render as pinned anymore.

2021-06-02 09:19 UTC, mayhem commented
Yup. that sounds right!

2021-06-02 09:21 UTC, mayhem approved these changes
Looking good!

2021-06-09 15:23 UTC, alastair approved these changes
looks good, let's merge it!

2021-06-09 16:16 UTC, merged