Improve pinnedRecording database queries + models
metabrainz/listenbrainz-server pull request #1510
Opened 2021-06-16 07:08 UTC by jdaok

This PR aims to make several improvements to the database models and queries in [PR 1503:](https://github.com/metabrainz/listenbrainz-server/pull/1503)

**1) Separate PinnedRecording and PinnedRecordingSubmit models**
  
  - When pinning a recording there wouldn't be a reason to set 'created' to anything other than the current datetime, but the query functions return a validated object and we wouldn't want the 'created' value to be replaced in the validator. 
  - From now on all pinned recordings would have a 'created' time set automatically to now(). (PinnedRecordingSubmit model)

**2) Unpin and Delete queries return True/False**: improves the responses and error messages at the API level when unpinning and deleting tracks.

**3) Get_pins_for_user_following()**

2021-06-16 07:08 UTC, pep8speaks commented
Hello @jdaok! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`listenbrainz/db/pinned_recording.py`](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py):

> [Line 46:61](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py#L46): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 67:1](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py#L67): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 69:85](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py#L69): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 70:90](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py#L70): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 134:1](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py#L134): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 135:131](https://github.com/metabrainz/listenbrainz-server/blob/9cb1ff952db767f19d2b883ec4da456fb9b2cf15/listenbrainz/db/pinned_recording.py#L135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 130 characters)

2021-06-18 08:37 UTC, mayhem requested changes
Other than our convo in IRC about having one class derive from the other, this looks pretty good.

2021-06-21 14:02 UTC, mayhem approved these changes
Looks good to me now, thanks!

2021-06-22 07:34 UTC, amCap1712 commented on listenbrainz/db/pinned_recording.py
> +        return result.rowcount == 1
While its unlikely the user will have more than one pin at a time (unless something is wrong on our end), I think its still better do this check better as `result.rowcount > 0`.

2021-06-22 07:46 UTC, amCap1712 approved these changes
LGTM

2021-06-22 07:53 UTC, merged