Error message for an incorrectly entered username
metabrainz/listenbrainz-server pull request #2117
Opened 2022-08-22 18:04 UTC by treeshateorcs

# Problem
https://tickets.metabrainz.org/browse/LB-1130

# Solution

# Action

2022-08-23 13:26 UTC, amCap1712 requested changes
Hi! Thanks for the PR but it seems incorrect in the current form. I suggest to make the changes as per the other comment and try and test locally if works as expected. Once that is done, I can help you add a test for this as well. Feel free to ask any other questions you may have.

2022-08-23 23:52 UTC, treeshateorcs commented on listenbrainz/webserver/static/js/src/lastfm/LastFMImporter.tsx
> +    } catch (wrong_username) {
oh no, how could i not think of placing wrong_username in a different scope! thank you! all done now

2022-08-25 12:01 UTC, amCap1712 commented
The latest changes look good to me. Thanks. 

I think we should also add a test for this to avoid regressions. Are you familiar with how to write a jest test?

It should test that the the correct error message is indeed displayed for the invalid username error. It will probably be similar to this test: https://github.com/metabrainz/listenbrainz-server/blob/d8a287962dd5e1523ee9d60ffa55c942a558ad38/listenbrainz/webserver/static/js/tests/lastfm/LastFMImporter.test.tsx#L120-L132

I can help you write one or add one myself if you prefer.

2022-08-26 07:48 UTC, treeshateorcs commented
okay, so i'm about to add a test. so far i have this, but i'm not sure about some things

```javascript
  it("should return user not found", async () => {
    instance.setState({ lastfmUsername: "nonexistentusernamedonttryathome" });

    await expect(instance.getTotalNumberOfScrobbles()).rejects.toThrowError(); 
    expect(instance.state.msg?.props.children).toMatch(  // not sure what this has to be
       "User not found" 
     ); 
  })
```

2022-08-26 07:59 UTC, treeshateorcs commented
or maybe this is better?

```javascript
  it("should return user not found", async () => {
    instance.setState({ lastfmUsername: "nonexistentusernamedonttryathome" });

    try {
      await instance.getTotalNumberOfScrobbles();
    } catch (err) {
      expect(err).toEqual(
        new Error(
          `User not found`
        )
      );
    }
  })
```


i've never seriously worked with javascript tbh

2022-08-26 19:06 UTC, amCap1712 approved these changes
Thanks for adding the test. It was missing a mock to generate the error message so I updated it.

2022-08-26 19:09 UTC, merged