LB-1306: Deleting a listen has an overlapping visual glitch
metabrainz/listenbrainz-server pull request #2564
Opened 2023-08-31 09:55 UTC by KasukabeDefenceForce

# Problem
When deleting a listen from my "Recent Listens" page, the deleted listen disappears and the following listen slides up - but it slides up too far, and overlaps the listen above temporarily before jumping down to the correct location.

# Solution
Made the animation look smoother and removed the overlapping visual glitch.

# Action

2023-09-11 11:39 UTC, MonkeyDo requested changes

2023-09-12 07:10 UTC, KasukabeDefenceForce commented on frontend/css/listens-page.less
>    @keyframes deleted-animation {
I made the required changes.

2023-09-12 17:28 UTC, MonkeyDo approved these changes

2023-09-12 17:29 UTC, MonkeyDo commented
Thanks @KasukabeDefenceForce !

2023-09-12 17:29 UTC, merged