LB-620: Document way to run specific integration tests
metabrainz/listenbrainz-server pull request #2823
Opened 2024-03-22 15:49 UTC by ykchong45

# Problem

[LB-620](https://tickets.metabrainz.org/browse/LB-620?filter=12410)

The documentation lacks information on running a single test file. 
It has been updated to provide clear instructions on executing a specific test file using the `./test.sh` script.

# Solution

1. Correct the function `is_unit_db_running` by fixing the container name queried in `docker ps`.
2. Remove the function `is_unit_db_exists`.
3. Adjust the logic so that when the test container is running, executing `./test.sh [path-to-test-file.py]` only runs the specified test and then exits, while retaining the test container for later runs.

2024-03-22 17:48 UTC, pep8speaks commented
Hello @ykchong45! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`listenbrainz/tests/integration/test_settings_views.py`](https://github.com/metabrainz/listenbrainz-server/blob/c42f09218a1645efd5f0dee14eb8c76ac12bbc2e/listenbrainz/tests/integration/test_settings_views.py):

> [Line 116:1](https://github.com/metabrainz/listenbrainz-server/blob/c42f09218a1645efd5f0dee14eb8c76ac12bbc2e/listenbrainz/tests/integration/test_settings_views.py#L116): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2024-04-12 15:45 UTC, MonkeyDo requested changes
Hi @ykchong45 !
Thanks for opening a PR.

I am not clear as to what the changes to the three non-documentation files achieve, looking at the PR title.

The only required change is adding the optional `[path-to-test-file.py]` in the documentation as well as possibly in the comments explaining the usage in the test.sh file.
None of the other changes make sense in the context of the problem stated. Could you please explain what they do, and why they are part of the same PR?

2024-04-30 12:03 UTC, amCap1712 approved these changes

2024-04-30 12:04 UTC, amCap1712 commented
LGTM, Thanks!

2024-04-30 12:04 UTC, merged

2024-05-03 02:57 UTC, ykchong45 commented
Thank you very much for helping me closing this pull request. 

For future's reference, this pull request updated the docs about testing, but in the meantime, I fixed a problem in the test script where it fails to execute a single test.