Dashboard ws listens
metabrainz/listenbrainz-server pull request #2920
Opened 2024-06-24 16:32 UTC by MonkeyDo

# Problem

When you load a user's dashboard and they are listening to music, you will see new listens arrive in a separate list.
Now if you navigate to another user's page the list will stay, showing the first user's listens.

# Solution
Reset the webSocketListens array when user name changes

Also did some minimal cleanup of some react dependencies warnings and memoized a function.

2024-06-24 17:47 UTC, kellnerd requested changes

2024-06-24 17:47 UTC, kellnerd commented on frontend/js/src/user/Dashboard.tsx
> +    // no exhaustive-deps because we only want ot run this on initial start
```suggestion
    // no exhaustive-deps because we only want to run this on initial start
```
:grin:

2024-06-24 17:47 UTC, kellnerd commented on frontend/js/src/user/Dashboard.tsx
> +            title="Coudn't parse the new listen as JSON: "
```suggestion
            title="Couldn't parse the new listen as JSON: "
```
Was already there before, but still

2024-06-25 18:14 UTC, anshg1214 approved these changes

2024-06-25 18:18 UTC, merged