Added exporting playlists to Apple functionality
metabrainz/listenbrainz-server pull request #2968
Opened 2024-08-28 11:09 UTC by rimma-kubanova

**Export to Apple Music**

**Frontend:**

- Added an "Export to Apple Music" button on the user interface
- Added API Callbacks in `APIService`

**Backend:**

* Added `export_to_apple_music` to `export_playlist` endpoint. `export_to_apple_music` calls troi
* Added export JSPF playlist to Apple Music

2024-10-21 10:34 UTC, MonkeyDo requested changes
Not sure whose review you were waiting for, but I think it's been long enough of a wait for me to jump in :)
Please excuse if I am unaware of some aspects of your project and some of the  suggestions below are incorrect.

Overall looks good, some details need to be addressed before I can properly test the feature.

2024-10-21 10:34 UTC, MonkeyDo commented on frontend/js/src/playlists/components/PlaylistMenu.tsx
> +  const showAppleMusicExportButton = spotifyAuth;
This does not look correct. should probably be using appelAuth instead of spotifyAuth?

2024-10-21 10:34 UTC, MonkeyDo commented on listenbrainz/webserver/views/playlist_api.py
> +    if service != "spotify" and service != "soundcloud" and service != "apple_music":
Just checking here: should this change also include soundcloud?
Might be missing a `elif service == "soundcloud":` around line 890 to support it?

2024-10-21 10:34 UTC, MonkeyDo commented on listenbrainz/webserver/views/playlist_api.py
>          raise APIBadRequest(f"Service {service} is not supported. We currently only support 'spotify'.")
Text here should be updated to add "and 'apple_music'" at the end
It is worth checking if there are other similar instances in this method where some text needs an update.

2024-10-21 10:34 UTC, MonkeyDo commented on listenbrainz/webserver/views/playlist_api.py
>          raise APIBadRequest(f"Service {service} is not supported. We currently only support 'spotify'.")
Same as above here, the error text needs to be updated. Please also check other text string in this method for completion.

2024-10-21 10:34 UTC, MonkeyDo commented on listenbrainz/webserver/views/playlist_api.py
> +        apple_service = AppleService()
Doesn't look right. Should it be this?
```suggestion
    elif service == "apple_music":
        apple_service = AppleService()
```

2024-10-22 08:11 UTC, rimma-kubanova commented
@MonkeyDo Hi! Thanks for your review!
I’ve made the necessary fixes and also added a unit test case for Apple as well. Sorry for the delay!

2025-01-15 14:31 UTC, MonkeyDo reviewed
@anshg1214 Overall it works fine, I asked someone on the LB chat to test it.

The issues I see:
- for me, with my apple music account "disabled" (i.e. not paying) here is the error I get when I try an export:
![image](https://github.com/user-attachments/assets/b444bf3a-19a2-4f11-ae97-9b733f185cf8)
The logs from the container:
```
2025-01-15 14:08:17,356 listenbrainz.webserver ERROR    Exception on /profile/music-services/soundcloud/callback/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/listenbrainz/listenbrainz/webserver/views/settings.py", line 214, in music_services_callback
    token = service.fetch_access_token(code)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/listenbrainz/listenbrainz/domain/brainz_service.py", line 64, in fetch_access_token
    return oauth.fetch_token(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
          ^^^^^^^^^^^^^
TypeError: CustomOAuth2Error.__init__() missing 1 required positional argument: 'error'
```
I guess it's related to auth rather than playlist exports, but I thought I'd write it here. The front-end error message could do with a more descriptive title than "Error"

- the user who tested the playlist export reported that only 15 out of 50 tracks were added to the applemusic playlist. I reckon this is an issue with troi rather than this PR, but again wanted to report it somewhere.
links to the playlists: https://test.listenbrainz.org/playlist/d9f440e8-1e89-46c3-89b4-49c883212ae6  and its counterpart  https://music.apple.com/ru/playlist/top-discoveries-of-2024-for-wileyfoxyx/pl.u-MDAWWgjuWKWyybk

2025-01-15 15:06 UTC, anshg1214 commented
@MonkeyDo The logs of the error are of a separate issue. The SoundCloud auth is broken right now. I'm checking the reason for it.

2025-01-16 16:24 UTC, anshg1214 commented
> for me, with my apple music account "disabled" (i.e. not paying) here is the error I get when I try an export:

I'll add a check in the frontend itself to check if the user is authorized to perform this operation

> the user who tested the playlist export reported that only 15 out of 50 tracks were added to the applemusic playlist.

Yes, I have also seen this error.

2025-01-16 17:08 UTC, merged