Feat: Added Volume Control Slider to BrainzPlayer
metabrainz/listenbrainz-server pull request #3097
Opened 2024-12-27 12:26 UTC by Suvid-Singhal

# Problem

Earlier, ListenBrainz used to play music in max volume by default. This feature aims to let users control the volume of music in ListenBrainz itself.
The feature request ticket was LB-1702.

# Solution
I created an input range component. Also added some hooks and states. The UI is basic as of now and can be improved further I believe.
The demo is attached below:

https://github.com/user-attachments/assets/b7efde23-8880-4e99-9323-cbd2b7c3f25e

# Action
I tested the new feature for YouTube and Spotify but couldn't test it for SoundCloud and Apple Music. I couldn't test it for SoundCloud as they are not accepting new application requests right now so couldn't get the API key. Couldn't test it for Apple Music as I don't have Apple Music premium 😅

If anyone could test it for these two platforms it would be great. Also, please suggest UI changes, if any.

P.S. It's my biggest open-source contribution till date. Thanks @anshg1214 for guiding and supporting me :)

2025-01-08 11:27 UTC, anshg1214 reviewed
Thank you for taking up this ticket. The functionality works as expected. But there are some improvements which can be done here.

2025-01-08 11:27 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
> +    );
How about instead of creating a consumer for the context, we pass down the volume as props?

It would simplify things and also prevent re-rendering whenever the context values are updated

2025-01-08 11:27 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
>    }
Adding a comment here as I cannot comment on [this code piece ](https://github.com/metabrainz/listenbrainz-server/pull/3097/files#diff-3a174aac201e54fa841962b156d84592132542e10d10f7eacb529c488df2a80eR443-R466). 

While playing a track on spotify you should also change the volume being set here.

2025-01-08 11:27 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
>    }
You should also add a listener for volume change, so that if someone changes volume on the spotify app, the changes are reflected here.

2025-01-08 11:27 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +function VolumeControlButton() {
Let's move this to a new file?

2025-01-08 11:27 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/BrainzPlayerContext.tsx
> +  payload?: any;
Instead of payload, you can use the data variable.

2025-01-08 11:27 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +  );
The volume slider is not visible on the mobile view.

![image](https://github.com/user-attachments/assets/0679eccb-d54d-4fc4-a4d5-7eac28cb8d4d)

2025-01-08 11:28 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
> +    );
This improvement can be made for all the players.

2025-01-09 07:23 UTC, Suvid-Singhal commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +  );
In mobile view, even the previous song button is also not visible. Could you please suggest improvements that can be done in order to accomodate the volume button properly?

2025-01-10 15:51 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +  );
I would say you probably want to hide it on mobile devices for now, and wait for #2940 to take care of the rest.

To hide on mobile you can use the bootstrap classes `hidden-xs`  or maybe `hidden-sm`, you will have to text different screen sizes.

2025-01-12 17:36 UTC, Suvid-Singhal commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +  );
Done @MonkeyDo :)
The volume slider is no longer visible on xs and sm viewports.

2025-01-13 19:05 UTC, MonkeyDo requested changes
UI looks good, thanks.
I took another look at the code and have a bit more feedback, sorry for trickling the feedback bit by bit!

2025-01-13 19:05 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/YoutubePlayer.tsx
> +    this.youtubePlayer?.setVolume(volume ?? 100);
Same as for the others, this shouldn't be called in the render function but rather after setting up `this.youtubePlayer`, probably in the `onReady` function

2025-01-13 19:05 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/SoundcloudPlayer.tsx
> +    this.soundcloudPlayer?.setVolume((volume ?? 100) / 100);
This shouldn't be called here but rather most likely in the `onReady` function, or when setting up soundcloudPlayer on line 145

2025-01-14 06:22 UTC, Suvid-Singhal commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
> +    this.spotifyPlayer?.setVolume((volume ?? 100) / 100);
It doesn't change the volume if I only set volume in the new window.Spotify.Player and not update it in render function.
I think that might be because that function is used to set up Spotify player initially with the given initial volume.
That's why I had to put volume state in render function of every player.

2025-01-14 09:44 UTC, Suvid-Singhal commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
>    }
Hi,
I can't think of any way to track changes in volume from the spotify app 🤔
I tried modifying the existing player_state_changed event listener but it doesnt seem to work.
Can you please help me out in this?
Thanks

2025-01-14 11:50 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
> +    this.spotifyPlayer?.setVolume((volume ?? 100) / 100);
according to the documentation you should indeed be able to set the volume in the Spotify.Player constructor: https://developer.spotify.com/documentation/web-playback-sdk/reference

2025-01-14 12:45 UTC, Suvid-Singhal commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
> +    this.spotifyPlayer?.setVolume((volume ?? 100) / 100);
Fixed for all the players :)

2025-01-14 12:48 UTC, Suvid-Singhal commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
>    }
> While playing a track on spotify you should also change the volume being set here.
Fixed this by putting setVolume in has_player_state_changed event handler. The volume update in spotify happens whenever this event is fired now.
I don't think so we can track the volume change in spotify app to update on brainzplayer for now.

2025-01-14 16:12 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
>    }
Here's a question for @anshg1214 : How do you wan to synchronize volume with spotify?
If the volume changes in spotify app and we manage to get the value, should it change the volume for BP?
If you change the volume for BP, should it change the value of spotify app volume?

That seems maybe a bit too intertwined

2025-01-14 16:47 UTC, anshg1214 commented on frontend/js/src/common/brainzplayer/SpotifyPlayer.tsx
>    }
Yes. If we can have that feature that'll be great. We do support change handler such that if someone changes track from the spotify app, the states are updated in BP.

However, if spotify does not support this, we can drop this for now.

2025-01-15 15:45 UTC, MonkeyDo requested changes
You found a good way to do volume setting in componentDidUpdate, albeit with a small prop check required. Nice work on that front!

However I think the UI needs some more work.

The input on the player bar does not look very good on desktop sizes. It is very wide for no reason, and its placement leaves to be desired. Not sure if you looked at it in desktop size, but it's massive and bright colored, it makes it look like a progress bar...
![image](https://github.com/user-attachments/assets/c33a6890-6c33-44e9-8c1d-06a3d4c70669)


Usually, what I expect from this type of media player is one of two things:
- a volume button, which on hover or click will show a vertical range input above it
![image](https://github.com/user-attachments/assets/bbea7a7e-53f5-4333-a58e-4622414426ab)
- a small horizontal range input like what you see on youtube, spotify, apple music in their respective player controls
![image](https://github.com/user-attachments/assets/26c74111-b2f3-42e9-b2a7-f3bd0d7bd176)
![image](https://github.com/user-attachments/assets/38adb368-6891-43d5-a4a4-0fd5994e21cf)
![image](https://github.com/user-attachments/assets/7366afc0-4575-45f1-9db9-14836f97b8bb)

Considering we already show the player queue by sliding it up (click the stacked horizontal bars in the player), maybe the first solution makes the most sense in this case. It would also work for smaller screen sizes more easily, as we would only need space for one extra volume icon in the player bar:
![image](https://github.com/user-attachments/assets/a46bce01-81bd-445f-b1b4-2999b17a510d)


Do let me know if you have questions or if you are unsure about anything, better to talk first to figure things out before implementing :)

2025-01-15 15:45 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/AppleMusicPlayer.tsx
> +    if (player) {
For each of these calls in componentDidUpdate, you need to check if the `volume` prop has changed:
```suggestion
    if (prevProps.volume !== volume && player) {
```

2025-01-15 15:45 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/VolumeControlButton.tsx
> +  };
You don't need a ref for this at all:
```suggestion
  const handleVolumeChange = (e: React.MouseEvent<HTMLInputElement>) => {
    dispatch({
      type: "VOLUME_CHANGE",
      data: e.currentTarget?.value ?? 100,
    });
  };
```

Don't forget to remove the ref prop on the input element

2025-01-15 15:45 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +        <VolumeControlButton />
For my proposal to turn this into a volume icon that you click/hover on to show the input, you would need to move this one line below.

2025-01-15 15:45 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/VolumeControlButton.tsx
> +    <input
Instead of rendering the input directly in here, I suggest rendering a volume icon. When clicking on the icon, the volume input will appear above it.
For CSS styles for the hidden/shown input, you can take inspiration from the player queue (the three horizontal bars in the player UI)
https://github.com/metabrainz/listenbrainz-server/blob/f40c908885229d42c5cb7716ea57a54d39ed2ca4/frontend/css/brainzplayer.less#L354C2-L370C4

2025-01-16 08:13 UTC, Suvid-Singhal commented
Made all the required changes. It now looks like this:

https://github.com/user-attachments/assets/a7e4f1d2-7121-4566-9c71-8847c911828b

2025-01-16 16:56 UTC, MonkeyDo requested changes
OK, I have a bunch more small suggestions, don't hate me :p
I think after this batch we'll be good, solid and consistent.

Here's where i ended up at:
![image](https://github.com/user-attachments/assets/ce184cae-6727-45b5-b7bd-56108c557133)

Thanks for your patience!

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +  z-index: 109;
This will put the volume component on top of the queue if it is open, otherwise users might not see that there is a component at all and think the button does nothing.
```suggestion
  z-index: 110;
```

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +  .volume-input {
Let's animate the transition between hidden and shown:
```suggestion
  bottom: -100px;
  transition: bottom 0.5s ease-in-out;
  .volume-input {
```

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +    width: 7em;
I think this is a bit wide, I suggest:
```suggestion
    width: 3.5em;
```

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +    transform: rotate(270deg);
I have a fun CSS trick for you today!
For vertical range inputs, you can use:
```suggestion
    writing-mode: vertical-rl;
    direction: rtl;
    margin: 1.5em 0.6em;
```

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +
Let's make some styles common to .volume and .queue.

These are the properties I can tell will help have a consistent look between the two:
```css
  transition: bottom 1s ease-in-out;
  background-color: #f8f8f8;
  border-top: 1px solid #ccc;
  box-shadow: -6px -1px 10px rgba(0, 0, 0, 0.2);
  &.show {
    bottom: @brainzplayer-height;
  }
```

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +.volume {
One more style suggestion to be applied to the whole website, so to be added to the frontend/css/main.less file:

```less
input[type='range'] {
    accent-color: @blue;
}
```

This will style the color of the range input:
![image](https://github.com/user-attachments/assets/c09c6c0c-aa2c-401c-91ec-21722d55b189)

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/css/brainzplayer.less
> +  right: 16em;
to go with my width changes:
```suggestion
  right: 17em;
```

2025-01-16 16:56 UTC, MonkeyDo commented on frontend/js/src/common/brainzplayer/BrainzPlayerUI.tsx
> +                className="hidden-sm hidden-xs"
After seeing it in action, I think it should only be
```suggestion
                className="hidden-xs"
```

2025-01-16 19:02 UTC, Suvid-Singhal commented on frontend/css/brainzplayer.less
> +  .volume-input {
I also thought of including transition for 0.5s initially but then dropped it later 😅

2025-01-17 11:16 UTC, MonkeyDo commented
OK, I see what I forgot to copy over from my experimentations :)

In the .volume css class, remove the `height` declaration entirely>
Should be left with a good looking input:
![image](https://github.com/user-attachments/assets/88a79598-1133-4297-9a09-2736b257aabe)

2025-01-17 12:06 UTC, Suvid-Singhal commented
Was having this issue after removing height declaration. But I fixed it by changing `bottom: -100px;` to `bottom: -12em;`

![Screenshot from 2025-01-17 17-29-58](https://github.com/user-attachments/assets/e4558384-631d-49b2-bdde-892c442216b7)

Now I feel that it looks perfect on testing. 😅

2025-01-17 14:03 UTC, MonkeyDo approved these changes
Thanks for the good work!
Everything looking fine now :rocket:

2025-01-17 14:05 UTC, merged